apiVersion: v1
name: secured-resources-diff
version: 0.0.1
home: https://github.com/OpusCapita/secured-resources-diff
maintainers:
  - name: Alexey Sergeev
    email: alexey.sergeev@opuscapita.com
    url: https://github.com/asergeev-sc
icon: https://opuscapita.github.io/styles/img/app-logo.svg
tillerVersion: ">2.8.0"
